version: '3'

services:
  llvm:
    container_name: FiTx
    tty: true
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - project_path=${FITX_ROOT}
        - linux_path=${LINUX_ROOT}
